version: "3.9"
volumes:
  app_data:

services:
  zerobot-plugin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
    ports:
      - "30110:3000"
    volumes:
      - app_data:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"] # Replace with your health check
      interval: 30s
      timeout: 10s
      retries: 3
